USE master;

IF DB_ID('XESmartTargetTest') IS NOT NULL
BEGIN
	ALTER DATABASE XESmartTargetTest SET SINGLE_USER WITH ROLLBACK IMMEDIATE;	
	DROP DATABASE XESmartTargetTest;
END
GO

CREATE DATABASE XESmartTargetTest;
GO

USE master;
GO

