{
 "title": "Workload Analysis",
 "time": { "from": "2021-06-11T07:07:35.476Z", "to": "2021-06-11T07:07:38.083Z" },
 "panels": [
  {
   "title": "CPU by principal name",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "µs" } },
   "yaxes": [
    { "format": "µs" }
   ],
   "targets": [
    {
     "rawSql": "SELECT time,\r\n    [server_principal_name], \r\n    SUM([tot_cpu]) AS tot_cpu\r\nFROM XERecipes.dbo.[Recipe_08_WorkloadAnalysis_grafana]\r\nWHERE $__timeFilter(time)\r\nGROUP BY \r\n    time,\r\n    $__timeGroup(time,'5m', NULL),\r\n    [server_principal_name]\r\nORDER BY 1,2;"
    }
   ]
  },
  {
   "title": "CPU by principal name",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "µs" } },
   "yaxes": [
    { "format": "µs" }
   ],
   "targets": [
    {
     "rawSql": "SELECT time,\r\n    [server_principal_name], \r\n    SUM([tot_cpu]) AS tot_cpu\r\nFROM XERecipes.dbo.[Recipe_08_WorkloadAnalysis_grafana]\r\nWHERE $__timeFilter(time)\r\nGROUP BY \r\n    time,\r\n    $__timeGroup(time,'5m', NULL),\r\n    [server_principal_name]\r\nORDER BY 1,2;"
    }
   ]
  },
  {
   "title": "Executions by principal name",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "rawSql": "SELECT time,\r\n    [server_principal_name], \r\n    --SUM([tot_cpu]) AS tot_cpu,\r\n    --SUM([tot_duration]) AS tot_duration\r\n    --SUM([tot_reads]) AS tot_reads, \r\n    --SUM([tot_writes]) AS tot_writes, \r\n    SUM([execution_count]) AS execution_count\r\nFROM XERecipes.dbo.[Recipe_08_WorkloadAnalysis_grafana]\r\nWHERE $__timeFilter(time)\r\nGROUP BY \r\n    time,\r\n    $__timeGroup(time,'5m', NULL),\r\n    [server_principal_name]\r\nORDER BY 1,2;"
    }
   ]
  },
  {
   "title": "Reads by principal name",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "rawSql": "SELECT time,\r\n    [server_principal_name], \r\n    --SUM([tot_cpu]) AS tot_cpu,\r\n    --SUM([tot_duration]) AS tot_duration\r\n    SUM([tot_reads]) AS tot_reads\r\n    --SUM([tot_writes]) AS tot_writes, \r\n    --SUM([execution_count]) AS execution_count\r\nFROM XERecipes.dbo.[Recipe_08_WorkloadAnalysis_grafana]\r\nWHERE $__timeFilter(time)\r\nGROUP BY \r\n    time,\r\n    $__timeGroup(time,'5m', NULL),\r\n    [server_principal_name]\r\nORDER BY 1,2;"
    }
   ]
  }
 ]
}