{
 "title": "SQL Server Events",
 "description": "Provides an overview of all the monitored instances",
 "tags": [
  "SQL Server",
  "Overview",
  "Menu"
 ],
 "time": { "from": "now-2d", "to": "now" },
 "templating": {
  "list": [
   { "name": "InfluxDB_Database", "label": "InfluxDB_Database", "query": "influxdb" },
   { "name": "InfluxDB_RetentionPolicy", "label": "InfluxDB_RetentionPolicy", "query": "standard" },
   {
    "name": "Var_Sql_Instance",
    "label": "Sql Server Instance",
    "query": "SHOW TAG VALUES WITH KEY = \"server_instance_name\""
   },
   { "name": "Var_Dsh_Deadlock_Detail", "query": "gwiiAt4Gk" },
   { "name": "Var_Dsh_Timeout_Detail", "query": "4nLhuDvGz" },
   { "name": "Var_Dsh_Blocking_Detail", "query": "WVUE9vDMz" }
  ]
 },
 "panels": [
  {
   "title": "Events Overview",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$col",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "sqlserver_events_errors",
     "query": "SELECT count(\"event_sequence\") AS \"Error Events\" FROM \"sqlserver_events_errors\" WHERE (\"server_instance_name\" =~ /^$Var_Sql_Instance$/) AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "event_sequence" ], "type": "field" },
       {
        "params": [],
        "type": "count"
       },
       { "params": [ "Error Events" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "server_instance_name", "operator": "=~", "value": "/^$Var_Sql_Instance$/" }
     ]
    },
    {
     "alias": "$col",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "sqlserver_events_deadlocks",
     "query": "SELECT count(\"xml_report\") AS \"Deadlocks\" FROM \"$InfluxDB_RetentionPolicy\".\"sqlserver_events_deadlocks\" WHERE $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "event_sequence" ], "type": "field" },
       {
        "params": [],
        "type": "count"
       },
       { "params": [ "Deadlocks" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "server_instance_name", "operator": "=~", "value": "/^$Var_Sql_Instance$/" }
     ]
    },
    {
     "alias": "$col",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "sqlserver_events_timeouts",
     "query": "SELECT count(\"xml_report\") AS \"Deadlocks\" FROM \"$InfluxDB_RetentionPolicy\".\"sqlserver_events_deadlocks\" WHERE $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "event_sequence" ], "type": "field" },
       {
        "params": [],
        "type": "count"
       },
       { "params": [ "Timeouts" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "server_instance_name", "operator": "=~", "value": "/^$Var_Sql_Instance$/" }
     ]
    },
    {
     "alias": "$col",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "sqlserver_events_blocking",
     "query": "SELECT count(\"xml_report\") AS \"Deadlocks\" FROM \"$InfluxDB_RetentionPolicy\".\"sqlserver_events_deadlocks\" WHERE $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "event_sequence" ], "type": "field" },
       {
        "params": [],
        "type": "count"
       },
       { "params": [ "Blocking" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "server_instance_name", "operator": "=~", "value": "/^$Var_Sql_Instance$/" }
     ]
    }
   ]
  },
  { "title": "Errors", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 } },
  {
   "title": "Error Events by Database",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$tag_database_name",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "database_name" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "sqlserver_events_errors",
     "query": "SELECT count(\"event_sequence\") AS \"Error Events\" FROM \"$InfluxDB_RetentionPolicy\".\"sqlserver_events_errors\" WHERE (\"server_instance_name\" =~ /^$Var_Sql_Instance$/) AND $timeFilter GROUP BY time($__interval), \"database_name\" fill(null)",
     "select": [
      [
       { "params": [ "event_sequence" ], "type": "field" },
       {
        "params": [],
        "type": "count"
       },
       { "params": [ "Error Events" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "server_instance_name", "operator": "=~", "value": "/^$Var_Sql_Instance$/" }
     ]
    }
   ]
  },
  {
   "title": "Events List",
   "type": "table",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "string" } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "*" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "sqlserver_events_errors",
     "query": "SELECT\n\t \"time\"\n\t,\"database_name\" AS \"Database\"\n\t,\"client_app_name\" AS \"Client App\"\n\t,\"client_hostname\" AS \"Client Host\"\n\t,\"server_principal_name\" AS \"Username\"\n\t,\"severity\" AS \"Error Severity\"\n\t,\"error_number\" AS \"Error Number\"\n\t,\"message\" AS \"Error Message\"\n\t,\"event_sequence\" AS \"Event Sequence\"\nFROM \"autogen\".\"sqlserver_events_errors\"\nWHERE\n\t(\"server_instance_name\" =~ /^$Var_Sql_Instance$/) \n\tAND $timeFilter",
     "select": [
      [
       { "params": [ "message" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "Error Message" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "server_instance_name", "operator": "=~", "value": "/^$Var_Sql_Instance$/" }
     ]
    }
   ]
  },
  { "title": "Blocking", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 27 } },
  {
   "title": "Blocking by Database",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "alias": "$tag_database_name",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "database_name" ], "type": "tag" },
      { "params": [ "0" ], "type": "fill" }
     ],
     "measurement": "sqlserver_events_blocking",
     "query": "SELECT sum(\"duration\") AS \"Block Duration\" FROM \"$InfluxDB_RetentionPolicy\".\"sqlserver_events_blocking\" WHERE (\"server_instance_name\" =~ /^$Var_Sql_Instance$/) AND $timeFilter GROUP BY time($__interval), \"database_name\" fill(null)",
     "select": [
      [
       { "params": [ "event_sequence" ], "type": "field" },
       {
        "params": [],
        "type": "count"
       }
      ]
     ],
     "tags": [
      { "key": "server_instance_name", "operator": "=~", "value": "/^$Var_Sql_Instance$/" }
     ]
    }
   ]
  },
  {
   "title": "Blocking",
   "type": "table",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "string" } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "*" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "sqlserver_events_blocking",
     "query": "SELECT\n\t time\n\t,\"event_sequence\" AS \"Event Sequence\"\n\t,\"database_name\" AS \"Database\"\n\t,\"server_principal_name\" AS \"Username\"\n\t,\"object_id\" AS \"Object ID\"\n\t,\"duration\" AS \"Duration\"\n\t,\"lock_mode\" AS \"Lock Mode\"\n\t,\"resource_owner_type\" AS \"Res Owner Type\"\nFROM autogen.\"sqlserver_events_blocking\" \nWHERE\n\t(\"server_instance_name\" =~ /^$Var_Sql_Instance$/)\n\tAND $timeFilter",
     "select": [
      [
       { "params": [ "*" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "server_instance_name", "operator": "=~", "value": "/^$Var_Sql_Instance$/" }
     ]
    }
   ]
  },
  { "title": "Deadlock", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 44 } },
  {
   "title": "Deadlock by Database",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 45 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$tag_database_name",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "database_name" ], "type": "tag" },
      { "params": [ "0" ], "type": "fill" }
     ],
     "measurement": "sqlserver_events_deadlocks",
     "select": [
      [
       { "params": [ "event_sequence" ], "type": "field" },
       {
        "params": [],
        "type": "count"
       },
       { "params": [ "Deadlock Events" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "server_instance_name", "operator": "=~", "value": "/^$Var_Sql_Instance$/" }
     ]
    }
   ]
  },
  {
   "title": "Deadlock list",
   "type": "table",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 54 },
   "fieldConfig": { "defaults": { "unit": "string" } },
   "targets": [
    {
     "alias": "$tag_database_name",
     "groupBy": [
      { "params": [ "database_name" ], "type": "tag" },
      { "params": [ "server_principal_name" ], "type": "tag" }
     ],
     "measurement": "sqlserver_events_deadlocks",
     "query": "SELECT \n\t \"time\"\n\t,\"event_sequence\" AS  \"Event Sequence\"\n\t,\"database_name\" AS \"Database\"\n\t,\"server_principal_name\" AS \"Username\"\nFROM autogen.\"sqlserver_events_deadlocks\" \nWHERE\n\t(\"server_instance_name\" =~ /^$Var_Sql_Instance$/) \n\tAND $timeFilter",
     "select": [
      [
       { "params": [ "event_sequence" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "server_instance_name", "operator": "=~", "value": "/^$Var_Sql_Instance$/" }
     ]
    }
   ]
  },
  { "title": "Timeouts", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 60 } },
  {
   "title": "Timeout by Database",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 61 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$tag_database_name",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "database_name" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "sqlserver_events_timeouts",
     "query": "SELECT count(\"event_sequence\") AS \"Error Events\" FROM \"$InfluxDB_RetentionPolicy\".\"sqlserver_events_errors\" WHERE (\"server_instance_name\" =~ /^$Var_Sql_Instance$/) AND $timeFilter GROUP BY time($__interval), \"database_name\" fill(null)",
     "select": [
      [
       { "params": [ "event_sequence" ], "type": "field" },
       {
        "params": [],
        "type": "count"
       },
       { "params": [ "Timeout Events" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "server_instance_name", "operator": "=~", "value": "/^$Var_Sql_Instance$/" }
     ]
    }
   ]
  },
  {
   "title": "Timeout list",
   "type": "table",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 69 },
   "fieldConfig": { "defaults": { "unit": "string" } },
   "targets": [
    {
     "alias": "$tag_database_name",
     "groupBy": [
      { "params": [ "database_name" ], "type": "tag" },
      { "params": [ "server_principal_name" ], "type": "tag" }
     ],
     "measurement": "sqlserver_events_deadlocks",
     "query": "SELECT\n\ttime\n\t,\"event_sequence\" AS \"Event Sequence\"\n\t,\"database_name\" AS \"Database\"\n\t,\"client_app_name\" AS \"Client App\"\n\t,\"server_principal_name\" AS \"Username\"\n\t,\"duration\" AS \"Duration\"\nFROM autogen.\"sqlserver_events_timeouts\" \nWHERE\n\t(\"server_instance_name\" =~ /^$Var_Sql_Instance$/) \n\tAND $timeFilter",
     "select": [
      [
       { "params": [ "event_sequence" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "server_instance_name", "operator": "=~", "value": "/^$Var_Sql_Instance$/" }
     ]
    }
   ]
  }
 ]
}